//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC08_SHBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public ThanhToan()
        {
            this.PhieuGiaoDiches = new HashSet<PhieuGiaoDich>();
        }
    
        public int idThanhToan { get; set; }
        public string tenThanhToan { get; set; }
    
        public virtual ICollection<PhieuGiaoDich> PhieuGiaoDiches { get; set; }
    }
}
