//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC08_SHBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vung
    {
        public Vung()
        {
            this.KhachSans = new HashSet<KhachSan>();
        }
    
        public int idVung { get; set; }
        public string tenVung { get; set; }
    
        public virtual ICollection<KhachSan> KhachSans { get; set; }
    }
}
